# chatbot_ml/donnees_chatbot.py

DONNEES_ENTRAINEMENT = [

    # ── Tâches en cours ──
    ("combien de tâches sont en cours",           "taches_en_cours"),
    ("affiche les tâches en cours",               "taches_en_cours"),
    ("liste des tâches actives",                  "taches_en_cours"),
    ("quelles tâches sont en cours",              "taches_en_cours"),
    ("tâches actives",                            "taches_en_cours"),
    ("tâches qui tournent",                       "taches_en_cours"),
    ("tâches non terminées",                      "taches_en_cours"),
    ("tâches ouvertes",                           "taches_en_cours"),
    ("combien de tâches en cours",                "taches_en_cours"),
    ("nombre de tâches en cours",                 "taches_en_cours"),
    ("tâches actuelles",                          "taches_en_cours"),
    ("tâches du moment",                          "taches_en_cours"),

    # ── Tâches terminées ──
    ("combien de tâches sont terminées",          "taches_terminees"),
    ("tâches finies",                             "taches_terminees"),
    ("tâches complétées",                         "taches_terminees"),
    ("tâches accomplies",                         "taches_terminees"),
    ("tâches clôturées",                          "taches_terminees"),
    ("tâches réalisées",                          "taches_terminees"),
    ("combien de tâches terminées",               "taches_terminees"),
    ("nombre de tâches terminées",                "taches_terminees"),
    ("tâches faites",                             "taches_terminees"),
    ("tâches achevées",                           "taches_terminees"),

    # ── Tâches bloquées ──
    ("tâches bloquées",                           "taches_bloquees"),
    ("quelles tâches sont bloquées",              "taches_bloquees"),
    ("affiche les blocages",                      "taches_bloquees"),
    ("problèmes sur les tâches",                  "taches_bloquees"),
    ("tâches en attente",                         "taches_bloquees"),
    ("tâches suspendues",                         "taches_bloquees"),
    ("tâches qui bloquent",                       "taches_bloquees"),
    ("quels sont les blocages",                   "taches_bloquees"),
    ("combien de tâches bloquées",                "taches_bloquees"),
    ("nombre de tâches bloquées",                 "taches_bloquees"),

    # ── Tâches urgentes ──
    ("tâches urgentes",                           "taches_urgentes"),
    ("tâches haute priorité",                     "taches_urgentes"),
    ("tâches critiques",                          "taches_urgentes"),
    ("tâches prioritaires",                       "taches_urgentes"),
    ("tâches importantes",                        "taches_urgentes"),
    ("tâches à traiter en premier",               "taches_urgentes"),
    ("priorité haute",                            "taches_urgentes"),
    ("tâches niveau urgent",                      "taches_urgentes"),
    ("combien de tâches urgentes",                "taches_urgentes"),
    ("nombre de tâches urgentes",                 "taches_urgentes"),

    # ── Tâches en retard ──
    ("tâches en retard",                          "taches_retard"),
    ("tâches dépassées",                          "taches_retard"),
    ("tâches hors délai",                         "taches_retard"),
    ("deadline dépassée",                         "taches_retard"),
    ("tâches non livrées à temps",                "taches_retard"),
    ("tâches qui ont dépassé la date",            "taches_retard"),
    ("retard sur les tâches",                     "taches_retard"),
    ("tâches en dépassement",                     "taches_retard"),
    ("combien de tâches en retard",               "taches_retard"),
    ("nombre de tâches en retard",                "taches_retard"),

    # ── Total tâches ──
    ("combien de tâches au total",                "taches_total"),
    ("nombre total de tâches",                    "taches_total"),
    ("total des tâches",                          "taches_total"),
    ("volume de tâches",                          "taches_total"),
    ("toutes les tâches",                         "taches_total"),
    ("combien des tâches",                        "taches_total"),
    ("combien de tâches",                         "taches_total"),
    ("nombre de tâches",                          "taches_total"),
    ("il y a combien de tâches",                  "taches_total"),
    ("c'est quoi le nombre de tâches",            "taches_total"),
    ("donne moi le nombre de tâches",             "taches_total"),
    ("liste toutes les tâches",                   "taches_total"),
    ("affiche toutes les tâches",                 "taches_total"),

    # ── Tâches basse priorité ──
    ("tâches basse priorité",                     "taches_basse_priorite"),
    ("tâches peu urgentes",                       "taches_basse_priorite"),
    ("tâches faible priorité",                    "taches_basse_priorite"),
    ("tâches non urgentes",                       "taches_basse_priorite"),
    ("tâches de priorité basse",                  "taches_basse_priorite"),
    ("tâches priorité faible",                    "taches_basse_priorite"),
    ("tâches niveau bas",                         "taches_basse_priorite"),
    ("tâches sans urgence",                       "taches_basse_priorite"),
    ("combien de tâches basse priorité",          "taches_basse_priorite"),
    ("affiche les tâches basse priorité",         "taches_basse_priorite"),

    # ── Tâches par employé ──
    ("combien de tâches a cet employé",           "taches_par_employe"),
    ("tâches assignées à un employé",             "taches_par_employe"),
    ("charge de travail d'un employé",            "taches_par_employe"),
    ("qui a combien de tâches",                   "taches_par_employe"),
    ("répartition des tâches",                    "taches_par_employe"),
    ("distribution des tâches",                   "taches_par_employe"),
    ("tâches par personne",                       "taches_par_employe"),
    ("combien de tâches par employé",             "taches_par_employe"),
    ("qui a quoi comme tâches",                   "taches_par_employe"),
    ("assignation des tâches",                    "taches_par_employe"),

    # ── Projets actifs ──
    ("combien de projets actifs",                 "projets_actifs"),
    ("liste des projets en cours",                "projets_actifs"),
    ("projets en cours",                          "projets_actifs"),
    ("projets ouverts",                           "projets_actifs"),
    ("projets actifs",                            "projets_actifs"),
    ("projets non terminés",                      "projets_actifs"),
    ("projets en cours d'exécution",              "projets_actifs"),
    ("combien de projets",                        "projets_actifs"),
    ("nombre de projets",                         "projets_actifs"),
    ("il y a combien de projets",                 "projets_actifs"),
    ("liste des projets",                         "projets_actifs"),
    ("affiche les projets",                       "projets_actifs"),
    ("tous les projets",                          "projets_actifs"),

    # ── Projets terminés ──
    ("projets terminés",                          "projets_termines"),
    ("projets finis",                             "projets_termines"),
    ("combien de projets terminés",               "projets_termines"),
    ("projets clôturés",                          "projets_termines"),
    ("projets livrés",                            "projets_termines"),
    ("projets complétés",                         "projets_termines"),
    ("nombre de projets terminés",                "projets_termines"),
    ("projets achevés",                           "projets_termines"),

    # ── Projets en retard ──
    ("projets en retard",                         "projets_retard"),
    ("projets en danger",                         "projets_retard"),
    ("projets à risque",                          "projets_retard"),
    ("projets qui dépassent la deadline",         "projets_retard"),
    ("projets hors délai",                        "projets_retard"),
    ("projets en dépassement",                    "projets_retard"),
    ("projets qui prennent du retard",            "projets_retard"),

    # ── Meilleur projet ──
    ("quel projet avance le mieux",               "meilleur_projet"),
    ("projet le plus avancé",                     "meilleur_projet"),
    ("meilleur projet",                           "meilleur_projet"),
    ("projet avec le plus de progression",        "meilleur_projet"),
    ("quel projet est le plus proche de la fin",  "meilleur_projet"),
    ("projet le plus performant",                 "meilleur_projet"),

    # ── Avancement projet ──
    ("avancement des projets",                    "progression_globale"),
    ("progression des projets",                   "progression_globale"),
    ("taux d'avancement",                         "progression_globale"),
    ("état d'avancement",                         "progression_globale"),
    ("où en sont les projets",                    "progression_globale"),
    ("pourcentage de complétion des projets",     "progression_globale"),
    ("avancement projet",                         "progression_globale"),
    ("progression projet",                        "progression_globale"),
    ("combien avancent les projets",              "progression_globale"),
    ("quel est l'avancement",                     "progression_globale"),
    ("état des projets",                          "progression_globale"),
    ("bilan des projets",                         "progression_globale"),

    # ── Employé surchargé ──
    ("qui est surchargé",                         "employe_surcharge"),
    ("quel employé a trop de tâches",             "employe_surcharge"),
    ("employé surchargé",                         "employe_surcharge"),
    ("qui travaille trop",                        "employe_surcharge"),
    ("employé avec le plus de tâches",            "employe_surcharge"),
    ("qui a la plus grande charge",               "employe_surcharge"),
    ("surcharge de travail",                      "employe_surcharge"),

    # ── Employé disponible ──
    ("qui a le moins de tâches",                  "employe_disponible"),
    ("employé disponible",                        "employe_disponible"),
    ("qui peut prendre une tâche",                "employe_disponible"),
    ("employé libre",                             "employe_disponible"),
    ("qui est disponible",                        "employe_disponible"),
    ("employé avec peu de tâches",                "employe_disponible"),
    ("qui peut prendre un projet",                "employe_disponible"),

    # ── Performance employés ──
    ("performance des employés",                  "performance_employes"),
    ("qui travaille le mieux",                    "performance_employes"),
    ("classement des employés",                   "performance_employes"),
    ("meilleur employé",                          "performance_employes"),
    ("employé le plus productif",                 "performance_employes"),
    ("taux de complétion par employé",            "performance_employes"),
    ("rendement des employés",                    "performance_employes"),

    # ── Stats générales ──
    ("statistiques générales",                    "stats_generales"),
    ("donne moi un résumé",                       "stats_generales"),
    ("état général",                              "stats_generales"),
    ("tableau de bord",                           "stats_generales"),
    ("résumé global",                             "stats_generales"),
    ("vue d'ensemble",                            "stats_generales"),
    ("bilan général",                             "stats_generales"),
    ("rapport global",                            "stats_generales"),

    # ── Progression globale ──
    ("progression globale",                       "progression_globale"),
    ("avancement global",                         "progression_globale"),
    ("pourcentage avancement",                    "progression_globale"),
    ("taux de complétion global",                 "progression_globale"),
    ("combien de tâches sont faites",             "progression_globale"),
    ("quel est le taux de réalisation",           "progression_globale"),

    # ── Tâches sans assignation ──
    ("tâches non assignées",                      "taches_non_assignees"),
    ("tâches sans responsable",                   "taches_non_assignees"),
    ("tâches orphelines",                         "taches_non_assignees"),
    ("tâches sans employé",                       "taches_non_assignees"),
    ("qui n'a pas de tâche assignée",             "taches_non_assignees"),
    ("tâches sans assignation",                   "taches_non_assignees"),
    ("tâches non attribuées",                     "taches_non_assignees"),
    ("combien de tâches sans responsable",        "taches_non_assignees"),
    ("tâches libres",                             "taches_non_assignees"),
    ("tâches à assigner",                         "taches_non_assignees"),

    # ── Projets sans tâches ──
    ("projets sans tâches",                       "projets_sans_taches"),
    ("projets vides",                             "projets_sans_taches"),
    ("projets sans activité",                     "projets_sans_taches"),
    ("projets non démarrés",                      "projets_sans_taches"),
    ("projets sans aucune tâche",                 "projets_sans_taches"),
    ("projets inactifs",                          "projets_sans_taches"),
    ("combien de projets sans tâches",            "projets_sans_taches"),
    ("projets sans contenu",                      "projets_sans_taches"),

    # ── Charge équipe ──
    ("charge de l'équipe",                        "charge_equipe"),
    ("répartition du travail",                    "charge_equipe"),
    ("équilibre des tâches",                      "charge_equipe"),
    ("comment est réparti le travail",            "charge_equipe"),
    ("charge globale de l'équipe",                "charge_equipe"),
    ("charge de travail équipe",                  "charge_equipe"),
    ("workload équipe",                           "charge_equipe"),
    ("charge moyenne par employé",                "charge_equipe"),
    ("combien de tâches par personne en moyenne", "charge_equipe"),
    ("bilan de charge",                           "charge_equipe"),

    # ── Salutations ──
    ("bonjour",                                   "salutation"),
    ("salut",                                     "salutation"),
    ("hello",                                     "salutation"),
    ("bonsoir",                                   "salutation"),
    ("bonne journée",                             "salutation"),
    ("hey",                                       "salutation"),
    ("coucou",                                    "salutation"),

    # ── Autres ──
    ("merci",                                     "remerciement"),
    ("au revoir",                                 "au_revoir"),
    ("à bientôt",                                 "au_revoir"),
    ("aide",                                      "aide"),
    ("que peux tu faire",                         "aide"),
    ("comment tu fonctionnes",                    "aide"),
    ("help",                                      "aide"),
    ("quelles questions puis je poser",           "aide"),
    ("liste des commandes",                       "aide"),
]
