<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412220518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activite CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE evenement_id evenement_id INT NOT NULL');
        $this->addSql('ALTER TABLE candidat ADD CONSTRAINT FK_6AB5B471A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uq_candidature_unique ON candidature');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY `fk_candidature_offre`');
        $this->addSql('ALTER TABLE candidature ADD lettre_motivation LONGTEXT DEFAULT NULL, ADD disponibilite VARCHAR(50) DEFAULT NULL, ADD pretention_salariale INT DEFAULT NULL, CHANGE date_candidature date_candidature DATE DEFAULT NULL, CHANGE offre_emploi_id offre_emploi_id INT NOT NULL, CHANGE cv_uploaded_at cv_uploaded_at DATETIME DEFAULT NULL, CHANGE contract_status contract_status VARCHAR(50) DEFAULT NULL');
        $this->addSql('DROP INDEX fk_candidature_offre ON candidature');
        $this->addSql('CREATE INDEX IDX_E33BD3B8B08996ED ON candidature (offre_emploi_id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT `fk_candidature_offre` FOREIGN KEY (offre_emploi_id) REFERENCES offre_emploi (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conge_tt DROP FOREIGN KEY `fk_conge_employe`');
        $this->addSql('ALTER TABLE conge_tt DROP FOREIGN KEY `fk_conge_employe`');
        $this->addSql('ALTER TABLE conge_tt CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE type_conge type_conge VARCHAR(50) NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE ocr_verified ocr_verified TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE conge_tt ADD CONSTRAINT FK_2877E6211B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('DROP INDEX fk_conge_employe ON conge_tt');
        $this->addSql('CREATE INDEX IDX_2877E6211B65292 ON conge_tt (employe_id)');
        $this->addSql('ALTER TABLE conge_tt ADD CONSTRAINT `fk_conge_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `contract_ibfk_1`');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY `contract_ibfk_2`');
        $this->addSql('ALTER TABLE contract CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE employe_id employe_id BIGINT DEFAULT NULL, CHANGE rh_id rh_id BIGINT DEFAULT NULL, CHANGE date_debut date_debut VARCHAR(255) NOT NULL, CHANGE date_fin date_fin VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE salaire_base salaire_base VARCHAR(255) DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX employe_id ON contract');
        $this->addSql('CREATE INDEX IDX_E98F28591B65292 ON contract (employe_id)');
        $this->addSql('DROP INDEX rh_id ON contract');
        $this->addSql('CREATE INDEX IDX_E98F285922A2877C ON contract (rh_id)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `contract_ibfk_1` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT `contract_ibfk_2` FOREIGN KEY (rh_id) REFERENCES rh (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY `fk_demande_service_employe`');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY `fk_demande_type`');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY `fk_demande_service_employe`');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY `fk_demande_type`');
        $this->addSql('ALTER TABLE demande_service CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE date_demande date_demande VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE employe_id employe_id BIGINT DEFAULT NULL, CHANGE etape_workflow etape_workflow VARCHAR(255) DEFAULT NULL, CHANGE date_derniere_etape date_derniere_etape VARCHAR(255) DEFAULT NULL, CHANGE priorite priorite VARCHAR(255) DEFAULT NULL, CHANGE deadline_reponse deadline_reponse VARCHAR(255) DEFAULT NULL, CHANGE sla_depasse sla_depasse VARCHAR(255) DEFAULT NULL, CHANGE type type INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT FK_D16A217D1B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT FK_D16A217D8CDE5729 FOREIGN KEY (type) REFERENCES type_service (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX fk_demande_service_employe ON demande_service');
        $this->addSql('CREATE INDEX IDX_D16A217D1B65292 ON demande_service (employe_id)');
        $this->addSql('DROP INDEX fk_demande_type ON demande_service');
        $this->addSql('CREATE INDEX IDX_D16A217D8CDE5729 ON demande_service (type)');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT `fk_demande_service_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT `fk_demande_type` FOREIGN KEY (type) REFERENCES type_service (id)');
        $this->addSql('DROP INDEX matricule ON employe');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F804D3B912B2DC9C ON employe (matricule)');
        $this->addSql('ALTER TABLE evenement DROP FOREIGN KEY `fk_evenement_rh`');
        $this->addSql('ALTER TABLE evenement CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE date_debut date_debut VARCHAR(255) NOT NULL, CHANGE date_fin date_fin VARCHAR(255) NOT NULL, CHANGE lieu lieu VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE rh_id rh_id BIGINT DEFAULT NULL, CHANGE image_url image_url VARCHAR(255) DEFAULT NULL, CHANGE latitude latitude VARCHAR(255) DEFAULT NULL, CHANGE longitude longitude VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX fk_evenement_rh ON evenement');
        $this->addSql('CREATE INDEX IDX_B26681E22A2877C ON evenement (rh_id)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT `fk_evenement_rh` FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY `fk_participation_employe`');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY `fk_participation_evenement`');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY `fk_participation_employe`');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY `fk_participation_evenement`');
        $this->addSql('ALTER TABLE event_participation CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE date_inscription date_inscription VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE evenement_id evenement_id INT DEFAULT NULL, CHANGE employe_id employe_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT FK_8F0C52E3FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id)');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT FK_8F0C52E31B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('DROP INDEX fk_participation_evenement ON event_participation');
        $this->addSql('CREATE INDEX IDX_8F0C52E3FD02F13 ON event_participation (evenement_id)');
        $this->addSql('DROP INDEX fk_participation_employe ON event_participation');
        $this->addSql('CREATE INDEX IDX_8F0C52E31B65292 ON event_participation (employe_id)');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT `fk_participation_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT `fk_participation_evenement` FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE messenger_messages CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE body body VARCHAR(255) NOT NULL, CHANGE headers headers VARCHAR(255) NOT NULL, CHANGE queue_name queue_name VARCHAR(255) NOT NULL, CHANGE created_at created_at VARCHAR(255) NOT NULL, CHANGE available_at available_at VARCHAR(255) NOT NULL, CHANGE delivered_at delivered_at VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY `fk_offre_rh`');
        $this->addSql('DROP INDEX uq_offre_unique ON offre_emploi');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY `fk_offre_rh`');
        $this->addSql('ALTER TABLE offre_emploi CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE localisation localisation VARCHAR(255) NOT NULL, CHANGE type_contrat type_contrat VARCHAR(100) NOT NULL, CHANGE statut statut VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT FK_132AD0D122A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX fk_offre_rh ON offre_emploi');
        $this->addSql('CREATE INDEX IDX_132AD0D122A2877C ON offre_emploi (rh_id)');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT `fk_offre_rh` FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE prime DROP FOREIGN KEY `fk_prime_contract`');
        $this->addSql('ALTER TABLE prime DROP FOREIGN KEY `fk_prime_contract`');
        $this->addSql('ALTER TABLE prime CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE montant montant VARCHAR(255) NOT NULL, CHANGE date_attribution date_attribution VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE contract_id contract_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE prime ADD CONSTRAINT FK_544B0F572576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('DROP INDEX fk_prime_contract ON prime');
        $this->addSql('CREATE INDEX IDX_544B0F572576E0FD ON prime (contract_id)');
        $this->addSql('ALTER TABLE prime ADD CONSTRAINT `fk_prime_contract` FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY `fk_projet_responsable`');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY `fk_projet_rh`');
        $this->addSql('ALTER TABLE projet CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE responsable_employe_id responsable_employe_id BIGINT DEFAULT NULL, CHANGE date_debut date_debut DATETIME NOT NULL, CHANGE date_fin date_fin DATETIME NOT NULL');
        $this->addSql('DROP INDEX fk_projet_rh ON projet');
        $this->addSql('CREATE INDEX IDX_50159CA922A2877C ON projet (rh_id)');
        $this->addSql('DROP INDEX fk_projet_responsable ON projet');
        $this->addSql('CREATE INDEX IDX_50159CA9F59FA192 ON projet (responsable_employe_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT `fk_projet_responsable` FOREIGN KEY (responsable_employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT `fk_projet_rh` FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY `fk_rating_employe`');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY `fk_rating_evenement`');
        $this->addSql('ALTER TABLE rating CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE evenement_id evenement_id INT DEFAULT NULL, CHANGE employe_id employe_id BIGINT DEFAULT NULL, CHANGE commentaire commentaire VARCHAR(255) NOT NULL, CHANGE etoiles etoiles VARCHAR(255) NOT NULL, CHANGE date_creation date_creation VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX fk_rating_evenement ON rating');
        $this->addSql('CREATE INDEX IDX_D8892622FD02F13 ON rating (evenement_id)');
        $this->addSql('DROP INDEX fk_rating_employe ON rating');
        $this->addSql('CREATE INDEX IDX_D88926221B65292 ON rating (employe_id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT `fk_rating_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT `fk_rating_evenement` FOREIGN KEY (evenement_id) REFERENCES evenement (id)');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `fk_reponse_employe`');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `fk_reponse_conge`');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `fk_reponse_demande`');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `fk_reponse_employe`');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `fk_reponse_rh`');
        $this->addSql('ALTER TABLE reponse CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE decision decision VARCHAR(255) NOT NULL, CHANGE rh_id rh_id BIGINT DEFAULT NULL, CHANGE employe_id employe_id BIGINT DEFAULT NULL, CHANGE conge_tt_id conge_tt_id INT DEFAULT NULL, CHANGE demande_service_id demande_service_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC71B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('DROP INDEX fk_reponse_rh ON reponse');
        $this->addSql('CREATE INDEX IDX_5FB6DEC722A2877C ON reponse (rh_id)');
        $this->addSql('DROP INDEX fk_reponse_employe ON reponse');
        $this->addSql('CREATE INDEX IDX_5FB6DEC71B65292 ON reponse (employe_id)');
        $this->addSql('DROP INDEX fk_reponse_conge ON reponse');
        $this->addSql('CREATE INDEX IDX_5FB6DEC7998B593A ON reponse (conge_tt_id)');
        $this->addSql('DROP INDEX fk_reponse_demande ON reponse');
        $this->addSql('CREATE INDEX IDX_5FB6DEC71B90A347 ON reponse (demande_service_id)');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `fk_reponse_conge` FOREIGN KEY (conge_tt_id) REFERENCES conge_tt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `fk_reponse_demande` FOREIGN KEY (demande_service_id) REFERENCES demande_service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `fk_reponse_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `fk_reponse_rh` FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE salaire DROP FOREIGN KEY `fk_salaire_contract`');
        $this->addSql('ALTER TABLE salaire DROP FOREIGN KEY `fk_salaire_contract`');
        $this->addSql('ALTER TABLE salaire CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE mois mois VARCHAR(255) NOT NULL, CHANGE annee annee VARCHAR(255) NOT NULL, CHANGE montant montant VARCHAR(255) NOT NULL, CHANGE date_paiement date_paiement VARCHAR(255) DEFAULT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE contract_id contract_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE salaire ADD CONSTRAINT FK_3BCBBD112576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('DROP INDEX fk_salaire_contract ON salaire');
        $this->addSql('CREATE INDEX IDX_3BCBBD112576E0FD ON salaire (contract_id)');
        $this->addSql('ALTER TABLE salaire ADD CONSTRAINT `fk_salaire_contract` FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `fk_tache_employe`');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `fk_tache_projet`');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `tache_ibfk_1`');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `fk_tache_employe`');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `fk_tache_projet`');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY `tache_ibfk_1`');
        $this->addSql('ALTER TABLE tache CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) NOT NULL, CHANGE projet_id projet_id INT NOT NULL, CHANGE prime_id prime_id INT DEFAULT NULL, CHANGE date_debut date_debut DATETIME NOT NULL, CHANGE date_fin date_fin DATETIME NOT NULL, CHANGE level level VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_93872075C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_938720751B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_9387207569247986 FOREIGN KEY (prime_id) REFERENCES prime (id)');
        $this->addSql('DROP INDEX fk_tache_projet ON tache');
        $this->addSql('CREATE INDEX IDX_93872075C18272 ON tache (projet_id)');
        $this->addSql('DROP INDEX fk_tache_employe ON tache');
        $this->addSql('CREATE INDEX IDX_938720751B65292 ON tache (employe_id)');
        $this->addSql('DROP INDEX fk_tache_prime ON tache');
        $this->addSql('CREATE INDEX IDX_9387207569247986 ON tache (prime_id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `fk_tache_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `fk_tache_projet` FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `tache_ibfk_1` FOREIGN KEY (prime_id) REFERENCES prime (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE type_service CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE nom nom VARCHAR(255) NOT NULL, CHANGE categorie categorie VARCHAR(255) NOT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users CHANGE statut statut VARCHAR(50) NOT NULL');
        $this->addSql('DROP INDEX email ON users');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activite CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE evenement_id evenement_id BIGINT NOT NULL');
        $this->addSql('ALTER TABLE candidat DROP FOREIGN KEY FK_6AB5B471A76ED395');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B8B08996ED');
        $this->addSql('ALTER TABLE candidature DROP lettre_motivation, DROP disponibilite, DROP pretention_salariale, CHANGE date_candidature date_candidature DATE NOT NULL, CHANGE cv_uploaded_at cv_uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE contract_status contract_status VARCHAR(50) DEFAULT \'NONE\', CHANGE offre_emploi_id offre_emploi_id BIGINT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uq_candidature_unique ON candidature (candidat_id, offre_emploi_id)');
        $this->addSql('DROP INDEX idx_e33bd3b8b08996ed ON candidature');
        $this->addSql('CREATE INDEX fk_candidature_offre ON candidature (offre_emploi_id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B8B08996ED FOREIGN KEY (offre_emploi_id) REFERENCES offre_emploi (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conge_tt DROP FOREIGN KEY FK_2877E6211B65292');
        $this->addSql('ALTER TABLE conge_tt DROP FOREIGN KEY FK_2877E6211B65292');
        $this->addSql('ALTER TABLE conge_tt CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE type_conge type_conge VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE ocr_verified ocr_verified TINYINT DEFAULT 0');
        $this->addSql('ALTER TABLE conge_tt ADD CONSTRAINT `fk_conge_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_2877e6211b65292 ON conge_tt');
        $this->addSql('CREATE INDEX fk_conge_employe ON conge_tt (employe_id)');
        $this->addSql('ALTER TABLE conge_tt ADD CONSTRAINT FK_2877E6211B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F28591B65292');
        $this->addSql('ALTER TABLE contract DROP FOREIGN KEY FK_E98F285922A2877C');
        $this->addSql('ALTER TABLE contract CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE date_debut date_debut DATE NOT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE salaire_base salaire_base NUMERIC(12, 2) DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE employe_id employe_id BIGINT NOT NULL, CHANGE rh_id rh_id BIGINT NOT NULL');
        $this->addSql('DROP INDEX idx_e98f28591b65292 ON contract');
        $this->addSql('CREATE INDEX employe_id ON contract (employe_id)');
        $this->addSql('DROP INDEX idx_e98f285922a2877c ON contract');
        $this->addSql('CREATE INDEX rh_id ON contract (rh_id)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F28591B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F285922A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY FK_D16A217D1B65292');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY FK_D16A217D8CDE5729');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY FK_D16A217D1B65292');
        $this->addSql('ALTER TABLE demande_service DROP FOREIGN KEY FK_D16A217D8CDE5729');
        $this->addSql('ALTER TABLE demande_service CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE date_demande date_demande DATE NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE etape_workflow etape_workflow VARCHAR(30) DEFAULT \'SOUMISE\', CHANGE date_derniere_etape date_derniere_etape DATE DEFAULT NULL, CHANGE priorite priorite VARCHAR(20) DEFAULT \'NORMAL\', CHANGE deadline_reponse deadline_reponse DATE DEFAULT NULL, CHANGE sla_depasse sla_depasse TINYINT DEFAULT 0, CHANGE employe_id employe_id BIGINT NOT NULL, CHANGE type type BIGINT NOT NULL');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT `fk_demande_service_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT `fk_demande_type` FOREIGN KEY (type) REFERENCES type_service (id)');
        $this->addSql('DROP INDEX idx_d16a217d1b65292 ON demande_service');
        $this->addSql('CREATE INDEX fk_demande_service_employe ON demande_service (employe_id)');
        $this->addSql('DROP INDEX idx_d16a217d8cde5729 ON demande_service');
        $this->addSql('CREATE INDEX fk_demande_type ON demande_service (type)');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT FK_D16A217D1B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE demande_service ADD CONSTRAINT FK_D16A217D8CDE5729 FOREIGN KEY (type) REFERENCES type_service (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_f804d3b912b2dc9c ON employe');
        $this->addSql('CREATE UNIQUE INDEX matricule ON employe (matricule)');
        $this->addSql('ALTER TABLE evenement DROP FOREIGN KEY FK_B26681E22A2877C');
        $this->addSql('ALTER TABLE evenement CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE date_debut date_debut DATETIME NOT NULL, CHANGE date_fin date_fin DATETIME NOT NULL, CHANGE lieu lieu VARCHAR(200) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE image_url image_url VARCHAR(500) DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL, CHANGE rh_id rh_id BIGINT NOT NULL');
        $this->addSql('DROP INDEX idx_b26681e22a2877c ON evenement');
        $this->addSql('CREATE INDEX fk_evenement_rh ON evenement (rh_id)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681E22A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY FK_8F0C52E3FD02F13');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY FK_8F0C52E31B65292');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY FK_8F0C52E3FD02F13');
        $this->addSql('ALTER TABLE event_participation DROP FOREIGN KEY FK_8F0C52E31B65292');
        $this->addSql('ALTER TABLE event_participation CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE date_inscription date_inscription DATE NOT NULL, CHANGE statut statut VARCHAR(60) NOT NULL, CHANGE evenement_id evenement_id BIGINT NOT NULL, CHANGE employe_id employe_id BIGINT NOT NULL');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT `fk_participation_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT `fk_participation_evenement` FOREIGN KEY (evenement_id) REFERENCES evenement (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_8f0c52e3fd02f13 ON event_participation');
        $this->addSql('CREATE INDEX fk_participation_evenement ON event_participation (evenement_id)');
        $this->addSql('DROP INDEX idx_8f0c52e31b65292 ON event_participation');
        $this->addSql('CREATE INDEX fk_participation_employe ON event_participation (employe_id)');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT FK_8F0C52E3FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id)');
        $this->addSql('ALTER TABLE event_participation ADD CONSTRAINT FK_8F0C52E31B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE messenger_messages MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE id id BIGINT NOT NULL, CHANGE body body LONGTEXT NOT NULL, CHANGE headers headers LONGTEXT NOT NULL, CHANGE queue_name queue_name VARCHAR(190) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE available_at available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', CHANGE delivered_at delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY FK_132AD0D122A2877C');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY FK_132AD0D122A2877C');
        $this->addSql('ALTER TABLE offre_emploi CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE localisation localisation VARCHAR(200) NOT NULL, CHANGE type_contrat type_contrat VARCHAR(80) NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE description description TEXT NOT NULL');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT `fk_offre_rh` FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_offre_unique ON offre_emploi (titre, localisation, type_contrat)');
        $this->addSql('DROP INDEX idx_132ad0d122a2877c ON offre_emploi');
        $this->addSql('CREATE INDEX fk_offre_rh ON offre_emploi (rh_id)');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT FK_132AD0D122A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prime DROP FOREIGN KEY FK_544B0F572576E0FD');
        $this->addSql('ALTER TABLE prime DROP FOREIGN KEY FK_544B0F572576E0FD');
        $this->addSql('ALTER TABLE prime CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE montant montant NUMERIC(12, 2) NOT NULL, CHANGE date_attribution date_attribution DATE NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE contract_id contract_id BIGINT NOT NULL');
        $this->addSql('ALTER TABLE prime ADD CONSTRAINT `fk_prime_contract` FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_544b0f572576e0fd ON prime');
        $this->addSql('CREATE INDEX fk_prime_contract ON prime (contract_id)');
        $this->addSql('ALTER TABLE prime ADD CONSTRAINT FK_544B0F572576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA922A2877C');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA9F59FA192');
        $this->addSql('ALTER TABLE projet CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE statut statut VARCHAR(10) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE date_debut date_debut DATE NOT NULL, CHANGE date_fin date_fin DATE NOT NULL, CHANGE responsable_employe_id responsable_employe_id BIGINT NOT NULL');
        $this->addSql('DROP INDEX idx_50159ca922a2877c ON projet');
        $this->addSql('CREATE INDEX fk_projet_rh ON projet (rh_id)');
        $this->addSql('DROP INDEX idx_50159ca9f59fa192 ON projet');
        $this->addSql('CREATE INDEX fk_projet_responsable ON projet (responsable_employe_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA922A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA9F59FA192 FOREIGN KEY (responsable_employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D8892622FD02F13');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D88926221B65292');
        $this->addSql('ALTER TABLE rating CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE commentaire commentaire TEXT NOT NULL, CHANGE etoiles etoiles INT NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE evenement_id evenement_id BIGINT NOT NULL, CHANGE employe_id employe_id BIGINT NOT NULL');
        $this->addSql('DROP INDEX idx_d8892622fd02f13 ON rating');
        $this->addSql('CREATE INDEX fk_rating_evenement ON rating (evenement_id)');
        $this->addSql('DROP INDEX idx_d88926221b65292 ON rating');
        $this->addSql('CREATE INDEX fk_rating_employe ON rating (employe_id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926221B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY FK_5FB6DEC71B65292');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY FK_5FB6DEC722A2877C');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY FK_5FB6DEC71B65292');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY FK_5FB6DEC7998B593A');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY FK_5FB6DEC71B90A347');
        $this->addSql('ALTER TABLE reponse CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE decision decision VARCHAR(60) NOT NULL, CHANGE rh_id rh_id BIGINT NOT NULL, CHANGE employe_id employe_id BIGINT NOT NULL, CHANGE conge_tt_id conge_tt_id BIGINT DEFAULT NULL, CHANGE demande_service_id demande_service_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `fk_reponse_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5fb6dec722a2877c ON reponse');
        $this->addSql('CREATE INDEX fk_reponse_rh ON reponse (rh_id)');
        $this->addSql('DROP INDEX idx_5fb6dec71b65292 ON reponse');
        $this->addSql('CREATE INDEX fk_reponse_employe ON reponse (employe_id)');
        $this->addSql('DROP INDEX idx_5fb6dec7998b593a ON reponse');
        $this->addSql('CREATE INDEX fk_reponse_conge ON reponse (conge_tt_id)');
        $this->addSql('DROP INDEX idx_5fb6dec71b90a347 ON reponse');
        $this->addSql('CREATE INDEX fk_reponse_demande ON reponse (demande_service_id)');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC722A2877C FOREIGN KEY (rh_id) REFERENCES rh (user_id)');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC71B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC7998B593A FOREIGN KEY (conge_tt_id) REFERENCES conge_tt (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT FK_5FB6DEC71B90A347 FOREIGN KEY (demande_service_id) REFERENCES demande_service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE salaire DROP FOREIGN KEY FK_3BCBBD112576E0FD');
        $this->addSql('ALTER TABLE salaire DROP FOREIGN KEY FK_3BCBBD112576E0FD');
        $this->addSql('ALTER TABLE salaire CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE mois mois INT NOT NULL, CHANGE annee annee INT NOT NULL, CHANGE montant montant NUMERIC(12, 2) NOT NULL, CHANGE date_paiement date_paiement DATE DEFAULT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE contract_id contract_id BIGINT NOT NULL');
        $this->addSql('ALTER TABLE salaire ADD CONSTRAINT `fk_salaire_contract` FOREIGN KEY (contract_id) REFERENCES contract (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_3bcbbd112576e0fd ON salaire');
        $this->addSql('CREATE INDEX fk_salaire_contract ON salaire (contract_id)');
        $this->addSql('ALTER TABLE salaire ADD CONSTRAINT FK_3BCBBD112576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_93872075C18272');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_938720751B65292');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_9387207569247986');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_93872075C18272');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_938720751B65292');
        $this->addSql('ALTER TABLE tache DROP FOREIGN KEY FK_9387207569247986');
        $this->addSql('ALTER TABLE tache CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE statut statut VARCHAR(10) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE date_debut date_debut DATE DEFAULT NULL, CHANGE date_fin date_fin DATE DEFAULT NULL, CHANGE level level INT DEFAULT NULL, CHANGE projet_id projet_id BIGINT NOT NULL, CHANGE prime_id prime_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `fk_tache_employe` FOREIGN KEY (employe_id) REFERENCES employe (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `fk_tache_projet` FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT `tache_ibfk_1` FOREIGN KEY (prime_id) REFERENCES prime (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_9387207569247986 ON tache');
        $this->addSql('CREATE INDEX fk_tache_prime ON tache (prime_id)');
        $this->addSql('DROP INDEX idx_93872075c18272 ON tache');
        $this->addSql('CREATE INDEX fk_tache_projet ON tache (projet_id)');
        $this->addSql('DROP INDEX idx_938720751b65292 ON tache');
        $this->addSql('CREATE INDEX fk_tache_employe ON tache (employe_id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_93872075C18272 FOREIGN KEY (projet_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_938720751B65292 FOREIGN KEY (employe_id) REFERENCES employe (user_id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_9387207569247986 FOREIGN KEY (prime_id) REFERENCES prime (id)');
        $this->addSql('ALTER TABLE type_service CHANGE id id BIGINT AUTO_INCREMENT NOT NULL, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE categorie categorie VARCHAR(100) NOT NULL, CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE users CHANGE statut statut VARCHAR(255) NOT NULL');
        $this->addSql('DROP INDEX uniq_1483a5e9e7927c74 ON users');
        $this->addSql('CREATE UNIQUE INDEX email ON users (email)');
    }
}
